# Generated by Django 3.2 on 2021-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('monthly_income', models.PositiveIntegerField(verbose_name='Monthly Income')),
                ('monthly_expenses', models.PositiveIntegerField(verbose_name='Monthly Expenses')),
                ('free_money', models.FloatField(verbose_name='Free Money')),
                ('dependents', models.PositiveIntegerField(verbose_name='Dependents')),
                ('external_liabilities', models.PositiveIntegerField(verbose_name='External Liabilities')),
                ('finished_loans', models.PositiveIntegerField(verbose_name='Finished Loans')),
                ('prev_loan_interaction', models.PositiveIntegerField(verbose_name='Previous Loan Interaction')),
                ('last_status', models.PositiveIntegerField(verbose_name='Last Contract Status')),
                ('debt_days', models.IntegerField(verbose_name='Debt Days')),
                ('is_bad_loan', models.BooleanField(editable=False, verbose_name='Is Bad Loan')),
                ('risk_score', models.FloatField(editable=False, verbose_name='Risk Score')),
                ('will_be_bad_loan', models.BooleanField(editable=False, verbose_name='Will Be Bad Loan')),
                ('risk_calculation_status', models.CharField(choices=[('Match', 'Match'), ('Error', 'Error'), ('Exception', 'Exception')], default='Match', editable=False, max_length=32, verbose_name='Risk Calculation Status')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('max_debt_days', models.PositiveIntegerField(verbose_name='Max Debt Days')),
                ('min_risk_score', models.FloatField(verbose_name='Min Risk Score')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDependentsConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanExternalLiabilitiesConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanFinishedLoansConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanFreeMoneyConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanLastContractStatusConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanMonthlyExpensesConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanMonthlyIncomeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_value', models.PositiveIntegerField(verbose_name='Upper Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPrevLoanInteractionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('weight', models.FloatField(default=0.5, verbose_name='Weight')),
            ],
        ),
    ]
