ID: str = 'ID'
AGE: str = 'Age'
MONTHLY_INCOME: str = 'Monthly Income'
MONTHLY_EXPENSES: str = 'Monthly Expenses'
FREE_MONEY: str = 'Free Money'
DEPENDENTS: str = 'Dependents'
EXTERNAL_LIABILITIES: str = 'External Liabilities'
FINISHED_LOANS: str = 'Finished Loans'
PREV_LOAN_INTERACTION: str = 'Previous Loan Interaction'
LAST_CONTRACT_STATUS: str = 'Last Contract Status'
DEBT_DAYS: str = 'Debt Days'
IS_BAD_LOAN: str = 'Is Bad Loan'
RISK_SCORE: str = 'Risk Score'
WILL_BE_BAD_LOAN: str = 'Will Be Bad Loan'
RISK_CALCULATION_STATUS: str = 'Risk Calculation Status'

VALUE: str = 'Value'
UPPER_VALUE: str = 'Upper Value'
WEIGHT: str = 'Weight'

CONFIG_MAX_DEBT_DAYS: str = 'Max Debt Days'
CONFIG_MIN_RISK_SCORE: str = 'Min Risk Score'
